package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// PendingRoot is a terraform root that has landed on main but has not been
// applied since. In validio-internal/infra merging deliberately applies
// nothing — the README's recipe ends "Actions → Terraform apply → Run
// workflow → pick the root" — so this is the half of the lifecycle that is
// otherwise only tracked in someone's head.
type PendingRoot struct {
	Root       string `json:"root"`
	Repo       string `json:"repo"`
	Commits    int    `json:"commits"` // substantive commits since the last apply
	NewestSHA  string `json:"newest_sha"`
	NewestWhen string `json:"newest_when"`
	CompareURL string `json:"compare_url"`
	Workflow   string `json:"workflow"` // dispatched when the entry is picked
}

// planRelevant lists the file shapes terraform actually reads. A README or a
// CLAUDE.md inside a root cannot change a plan, so a commit touching only
// those is not a reason to apply anything.
//
// Deliberately narrow on the non-.tf entries: a bare ".yml" would match the
// .gitlab-ci.yml files sitting in every root before the CI migration, and a
// bare ".json" matches any data file. Only .env-exec.yaml earns its place,
// because it supplies the environment the provider credentials come from.
var planRelevant = []string{".tf", ".tfvars", ".tf.json", ".tftpl"}

func planRelevantFile(name string) bool {
	if filepath.Base(name) == ".env-exec.yaml" {
		return true
	}
	for _, ext := range planRelevant {
		if strings.HasSuffix(name, ext) {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Telling a real change from a cosmetic one
// ---------------------------------------------------------------------------

// stripComment removes an HCL end-of-line comment, but only one that starts
// outside a string literal. Without the quote tracking, every line holding a
// URL loses everything from the "//" of "https://" and reads as changed —
// which matters here because the comments being edited are mostly URLs.
func stripComment(line string) string {
	var b strings.Builder
	inStr := false
	for i := 0; i < len(line); i++ {
		c := line[i]
		if inStr {
			if c == '\\' && i+1 < len(line) {
				b.WriteByte(c)
				b.WriteByte(line[i+1])
				i++
				continue
			}
			if c == '"' {
				inStr = false
			}
			b.WriteByte(c)
			continue
		}
		switch {
		case c == '"':
			inStr = true
			b.WriteByte(c)
		case c == '#':
			return normalizeSpace(b.String())
		case c == '/' && i+1 < len(line) && line[i+1] == '/':
			return normalizeSpace(b.String())
		default:
			b.WriteByte(c)
		}
	}
	return normalizeSpace(b.String())
}

func normalizeSpace(s string) string { return strings.Join(strings.Fields(s), " ") }

// substantive reports whether a patch changes anything terraform would act
// on. It strips comments from both sides and compares what is left.
//
// Everything uncertain is called substantive: a false "needs applying" costs
// a plan, a false "all clear" hides a real change. So an absent patch (too
// large, binary, renamed) and any block comment both count as substantive
// rather than being guessed at.
func substantive(patch string) bool {
	if patch == "" {
		return true
	}
	if strings.Contains(patch, "/*") || strings.Contains(patch, "*/") {
		return true
	}
	var minus, plus []string
	for _, line := range strings.Split(patch, "\n") {
		switch {
		case strings.HasPrefix(line, "---"), strings.HasPrefix(line, "+++"):
			continue
		case strings.HasPrefix(line, "-"):
			if s := stripComment(line[1:]); s != "" {
				minus = append(minus, s)
			}
		case strings.HasPrefix(line, "+"):
			if s := stripComment(line[1:]); s != "" {
				plus = append(plus, s)
			}
		}
	}
	sort.Strings(minus)
	sort.Strings(plus)
	if len(minus) != len(plus) {
		return true
	}
	for i := range minus {
		if minus[i] != plus[i] {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// The root list
// ---------------------------------------------------------------------------

// fetchRoots reads the root list out of the dispatch workflow's `root` choice
// input. That list is generated by .github/scripts/list-roots.sh and a PR
// check (`list-roots.sh --check-apply-workflow`) fails if it goes stale, so
// the workflow file is an authoritative mirror of the real roots — and one
// API call instead of cloning the repo to grep for backend "gcs".
func fetchRoots(repo, workflow string) ([]string, error) {
	var resp struct {
		Content string `json:"content"`
	}
	path := fmt.Sprintf("/repos/%s/contents/.github/workflows/%s", repo, workflow)
	if err := ghJSON(&resp, path); err != nil {
		return nil, err
	}
	raw, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(resp.Content, "\n", ""))
	if err != nil {
		return nil, fmt.Errorf("decoding %s: %w", workflow, err)
	}

	// Walk the `options:` block of the workflow_dispatch input and take the
	// "- value" entries until the indentation breaks out of the list.
	var roots []string
	inOptions := false
	for _, line := range strings.Split(string(raw), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "options:") {
			inOptions = true
			continue
		}
		if !inOptions {
			continue
		}
		if strings.HasPrefix(trimmed, "#") || trimmed == "" {
			continue
		}
		if !strings.HasPrefix(trimmed, "- ") {
			break
		}
		roots = append(roots, strings.Trim(strings.TrimPrefix(trimmed, "- "), `"'`))
	}
	if len(roots) == 0 {
		return nil, fmt.Errorf("no root options found in %s", workflow)
	}
	sort.Strings(roots)
	return roots, nil
}

// rootsForFile maps a changed path to the roots it affects, mirroring
// .github/scripts/changed-roots.sh — including its one special case, where a
// shared dashboard template fans out to every monitoring root that renders it
// via templatefile().
func rootsForFile(name string, roots []string) []string {
	var out []string
	for _, r := range roots {
		if strings.HasPrefix(name, r+"/") {
			out = append(out, r)
		}
	}
	if strings.HasPrefix(name, "google/_dashboards/") {
		for _, r := range roots {
			if strings.HasPrefix(r, "google/monitoring-") {
				out = append(out, r)
			}
		}
	}
	return out
}

// ---------------------------------------------------------------------------
// Commit cache — a commit is immutable, so this never expires
// ---------------------------------------------------------------------------

type commitDetail struct {
	SHA   string `json:"sha"`
	Files []struct {
		Filename string `json:"filename"`
		Patch    string `json:"patch"`
	} `json:"files"`
}

func commitCachePath(repo, sha string) string {
	safe := strings.ReplaceAll(repo, "/", "-")
	return filepath.Join(filepath.Dir(repoCachePath()), "commits", safe, sha+".json")
}

// commitFiles returns the plan-relevant files a commit changed substantively.
// Results are cached on disk forever: a commit's contents cannot change, so
// only genuinely new SHAs ever cost an API call.
func commitFiles(repo, sha string) ([]string, error) {
	path := commitCachePath(repo, sha)
	if data, err := os.ReadFile(path); err == nil {
		var cached []string
		if json.Unmarshal(data, &cached) == nil {
			return cached, nil
		}
	}

	var c commitDetail
	if err := ghJSON(&c, fmt.Sprintf("/repos/%s/commits/%s", repo, sha)); err != nil {
		return nil, err
	}
	var changed []string
	for _, f := range c.Files {
		if !planRelevantFile(f.Filename) {
			continue
		}
		if substantive(f.Patch) {
			changed = append(changed, f.Filename)
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err == nil {
		if data, err := json.Marshal(changed); err == nil {
			if err := os.WriteFile(path, data, 0600); err != nil {
				log.Printf("Error caching commit %s: %s", sha, err)
			}
		}
	}
	return changed, nil
}

// ---------------------------------------------------------------------------
// Working out what is unapplied
// ---------------------------------------------------------------------------

type mainCommit struct {
	SHA    string `json:"sha"`
	Commit struct {
		Committer struct {
			Date string `json:"date"`
		} `json:"committer"`
		Message string `json:"message"`
	} `json:"commit"`
}

// lastApplied maps root -> head_sha of its most recent successful apply.
//
// The root is recovered from the run's display_title, which comes from
// apply.yml's `run-name: "terraform apply ${{ inputs.root }} (@${{ github.actor }})"`.
// If that line ever changes upstream, this stops matching and roots simply
// look never-applied — over-reporting, which is the safe direction.
func lastApplied(repo, workflow string, roots []string) (map[string]string, error) {
	var resp struct {
		WorkflowRuns []struct {
			DisplayTitle string `json:"display_title"`
			HeadSHA      string `json:"head_sha"`
			Conclusion   string `json:"conclusion"`
		} `json:"workflow_runs"`
	}
	path := fmt.Sprintf("/repos/%s/actions/workflows/%s/runs?status=success&per_page=100", repo, workflow)
	if err := ghJSON(&resp, path); err != nil {
		return nil, err
	}

	known := make(map[string]bool, len(roots))
	for _, r := range roots {
		known[r] = true
	}

	// Runs come back newest first, so the first hit per root wins.
	out := make(map[string]string)
	for _, r := range resp.WorkflowRuns {
		if r.Conclusion != "success" {
			continue
		}
		root := parseRunRoot(r.DisplayTitle)
		if root == "" || !known[root] || out[root] != "" {
			continue
		}
		out[root] = r.HeadSHA
	}
	return out, nil
}

// parseRunRoot pulls the root out of "terraform apply <root> (@<actor>)".
// Anything not matching that shape is skipped rather than guessed at.
func parseRunRoot(title string) string {
	const prefix = "terraform apply "
	if !strings.HasPrefix(title, prefix) {
		return ""
	}
	rest := strings.TrimPrefix(title, prefix)
	i := strings.Index(rest, " (@")
	if i < 0 {
		return ""
	}
	return strings.TrimSpace(rest[:i])
}

// fetchPending returns the roots with substantive commits on main that have
// not been applied since.
func fetchPending(repo, workflow string, window time.Duration, includeUnapplied bool) ([]PendingRoot, error) {
	roots, err := fetchRoots(repo, workflow)
	if err != nil {
		return nil, fmt.Errorf("root list: %w", err)
	}

	since := time.Now().Add(-window).UTC().Format(time.RFC3339)
	var commits []mainCommit
	listPath := fmt.Sprintf("/repos/%s/commits?sha=main&since=%s&per_page=100", repo, since)
	if err := ghJSON(&commits, listPath); err != nil {
		return nil, fmt.Errorf("commit list: %w", err)
	}
	if len(commits) == 0 {
		return nil, nil
	}

	applied, err := lastApplied(repo, workflow, roots)
	if err != nil {
		return nil, fmt.Errorf("apply history: %w", err)
	}

	// commits is newest-first. cutoff[root] is the index of that root's last
	// applied commit; everything before it in the slice is newer, so unapplied.
	// Using position rather than timestamps is exact: an apply's plan runs some
	// time after the dispatch, so comparing clocks would misjudge the boundary.
	cutoff := make(map[string]int, len(roots))
	for _, root := range roots {
		cutoff[root] = len(commits) // nothing applied inside the window
		if sha := applied[root]; sha != "" {
			for i, c := range commits {
				if c.SHA == sha {
					cutoff[root] = i
					break
				}
			}
		}
	}

	type acc struct {
		count      int
		newestSHA  string
		newestWhen string
	}
	hits := make(map[string]*acc)

	for i, c := range commits {
		files, err := commitFiles(repo, c.SHA)
		if err != nil {
			// One unreadable commit must not invent a clean result.
			return nil, fmt.Errorf("commit %s: %w", c.SHA[:7], err)
		}
		touched := make(map[string]bool)
		for _, f := range files {
			for _, r := range rootsForFile(f, roots) {
				touched[r] = true
			}
		}
		for root := range touched {
			if i >= cutoff[root] {
				continue // already applied
			}
			// A root with no apply history gives us no baseline, so "has
			// commits in the window" says nothing about whether it is behind
			// — it mostly means nobody has applied it through this workflow
			// yet. Claiming those are pending buries the real signal: right
			// after the CI migration that was 37 of 39 roots, every one of
			// them pointing at the migration commit itself.
			if !includeUnapplied && applied[root] == "" {
				continue
			}
			a := hits[root]
			if a == nil {
				a = &acc{newestSHA: c.SHA, newestWhen: c.Commit.Committer.Date}
				hits[root] = a
			}
			a.count++
		}
	}

	var out []PendingRoot
	for root, a := range hits {
		base := applied[root]
		if base == "" {
			base = commits[len(commits)-1].SHA
		}
		out = append(out, PendingRoot{
			Root:       root,
			Repo:       repo,
			Commits:    a.count,
			NewestSHA:  a.newestSHA,
			NewestWhen: a.newestWhen,
			CompareURL: fmt.Sprintf("https://github.com/%s/compare/%s...main", repo, base),
			Workflow:   workflow,
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Root < out[j].Root })
	return out, nil
}

// ---------------------------------------------------------------------------
// notify + dispatch
// ---------------------------------------------------------------------------

var (
	seenPending      = make(map[string]bool)
	pendingBaselined = false
)

// notifyPending fires once per root that has newly fallen behind main. Same
// baseline-on-first-poll rule as the other two notifiers, so a restart does
// not re-announce a backlog that was already there.
func notifyPending(pending []PendingRoot, enabled bool) {
	present := make(map[string]bool, len(pending))
	for _, p := range pending {
		present[p.Root] = true
	}
	if !pendingBaselined {
		seenPending = present
		pendingBaselined = true
		return
	}
	for _, p := range pending {
		if seenPending[p.Root] {
			continue
		}
		seenPending[p.Root] = true
		if !enabled {
			continue
		}
		notifySend("Terraform root needs applying",
			fmt.Sprintf("[%s] %s · %d commit(s) since last apply", p.Repo, p.Root, p.Commits))
	}
	for root := range seenPending {
		if !present[root] {
			delete(seenPending, root)
		}
	}
}

// dispatchApply starts the apply workflow for one root. This only ever gets
// as far as a plan: the workflow's apply job sits behind the `apply`
// environment's required reviewers, which the pill surfaces separately. So a
// mis-selection costs a plan, never a deploy.
func dispatchApply(p PendingRoot) {
	cmd := ghCommand("workflow", "run", p.Workflow, "--repo", p.Repo, "-f", "root="+p.Root)
	if out, err := cmd.CombinedOutput(); err != nil {
		log.Printf("Error dispatching apply for %s: %s: %s", p.Root, err, strings.TrimSpace(string(out)))
		notifySend("Terraform apply dispatch failed", fmt.Sprintf("[%s] %s", p.Repo, p.Root))
		return
	}
	notifySend("Terraform apply dispatched",
		fmt.Sprintf("[%s] %s · waiting for the plan", p.Repo, p.Root))
}
